#!/usr/bin/env python3
"""Generate the PWA manifest and service worker from the release contract."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
RELEASE = ROOT / "release-manifest.json"
WEBMANIFEST = ROOT / "manifest.webmanifest"
SERVICE_WORKER = ROOT / "sw.js"
SITEMAP = ROOT / "sitemap.xml"
ROBOTS = ROOT / "robots.txt"
NOINDEX_ROUTES = {"/map/", "/journey/", "/test/", "/build/", "/atlas/", "/five-plus-one/"}


def contract() -> dict[Path, str]:
    release = json.loads(RELEASE.read_text(encoding="utf-8"))
    available = {row["path"] for row in release["routes"]}
    preferred = [
        "/", "/discoveries/",
        "/discoveries/degrees-of-freedom/", "/discoveries/reality-gradient/",
        "/discoveries/burrisphere/", "/discoveries/mass-shell/",
        "/discoveries/ladder/", "/discoveries/nonduality/",
        "/discoveries/game/", "/discoveries/paradoxes/",
        "/discoveries/universalizability/", "/discoveries/is-ought/",
        "/plainly/", "/practice/", "/record/", "/about/", "/offline/",
    ]
    routes = [route for route in preferred if route in available]
    routes += [
        "/manifest.webmanifest", "/assets/css/xai.css", "/assets/js/pwa.js",
        "/assets/icons/icon-192.png", "/assets/icons/icon-512.png",
    ]
    digest = hashlib.sha256(json.dumps(routes, separators=(",", ":")).encode("utf-8"))
    cache_inputs = [row["file"] for row in release["routes"]] + release["assetFiles"] + ["release-manifest.json"]
    for rel in sorted(set(cache_inputs)):
        path = ROOT / rel
        digest.update(rel.encode("utf-8") + b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    cache = "emergentism-" + digest.hexdigest()[:12]

    webmanifest = {
        "name": "Emergentism — A Compass, Not a Cathedral",
        "short_name": "Emergentism",
        "description": "A tier-honest lens for emergence, agency, consequence, and return.",
        "id": "/compass/",
        "start_url": "/",
        "scope": "/",
        "display": "standalone",
        "background_color": "#050505",
        "theme_color": "#050505",
        "icons": [
            {"src": "/assets/icons/icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "/assets/icons/icon-512.png", "sizes": "512x512", "type": "image/png"},
            {"src": "/assets/icons/maskable-512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable"},
        ],
    }
    manifest_text = json.dumps(webmanifest, indent=1, ensure_ascii=False) + "\n"
    routes_text = json.dumps(routes, indent=2, ensure_ascii=False)
    sw_text = f"""// Generated by build_pwa.py from release-manifest.json.
const CACHE = {json.dumps(cache)};
const PRECACHE = {routes_text};

self.addEventListener('install', (event) => {{
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
  self.skipWaiting();
}});

self.addEventListener('activate', (event) => {{
  event.waitUntil(caches.keys().then((keys) => Promise.all(
    keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))
  )));
  self.clients.claim();
}});

self.addEventListener('fetch', (event) => {{
  if (event.request.method !== 'GET' || new URL(event.request.url).origin !== location.origin) return;
  if (event.request.mode === 'navigate') {{
    event.respondWith(fetch(event.request).then((response) => {{
      const copy = response.clone();
      caches.open(CACHE).then((cache) => cache.put(event.request, copy));
      return response;
    }}).catch(() => caches.match(event.request).then((hit) => hit || caches.match('/offline/'))));
    return;
  }}
  event.respondWith(caches.match(event.request).then((hit) => hit || fetch(event.request)));
}});
"""
    public_routes = [
        row["path"] for row in release["routes"]
        if row["path"] not in {"/404/", "/offline/"} | NOINDEX_ROUTES
    ]
    sitemap_rows = []
    for route in public_routes:
        priority = "1.0" if route == "/" else ("0.9" if route.startswith("/discoveries/") else "0.6")
        loc = html.escape("https://www.emergentism.org" + route)
        sitemap_rows.append(f"  <url><loc>{loc}</loc><priority>{priority}</priority></url>")
    sitemap_text = "\n".join([
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        *sitemap_rows,
        '</urlset>',
        '',
    ])
    robots_text = "User-agent: *\nAllow: /\nDisallow: /90_ARCHIVE/\n\nSitemap: https://www.emergentism.org/sitemap.xml\n"
    return {
        WEBMANIFEST: manifest_text,
        SERVICE_WORKER: sw_text,
        SITEMAP: sitemap_text,
        ROBOTS: robots_text,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = contract()
    if args.check:
        drift = [path.name for path, text in expected.items() if not path.exists() or path.read_text(encoding="utf-8") != text]
        if drift:
            print("PWA drift: " + ", ".join(drift))
            return 1
        print("PWA: clean")
        return 0
    for path, text in expected.items():
        path.write_text(text, encoding="utf-8")
    print("PWA: manifest and service worker generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
