#!/usr/bin/env python3
"""Give every served page an Open Graph card, derived from what it already declares.

360 of 391 served pages had no og:image, so pasting any of them into a chat produced a
bare link. Every page already has a unique <title> and <meta name="description">; this
derives the card from those rather than inventing copy.

Idempotent: injected between markers, so rerunning replaces rather than duplicates.
Pages that already hand-authored their og tags are left completely alone — 31 of them,
several with bespoke og:title and og:description worth keeping.

Usage: python3 -B build_social_cards.py          write
       python3 -B build_social_cards.py --check  verify, write nothing
"""
from __future__ import annotations
import html, os, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SKIP = ("/.vercel", "/node_modules", "/book-pwa", "/_STAGING", "/docs", "/_PLANS", "/.git")

# TWO EXCLUSION CLASSES THE FIRST VERSION IGNORED, and both failed the site gate within a
# minute of running:
#
#  1. WITHHELD ARTIFACTS carry a pinned sha256 in withheld-routes.json. Touching one is a
#     custody breach, and predeploy_check.py is right to refuse it. They are not served.
#  2. GENERATED PAGES (the D0-D6 spine and /dimensions/) are produced by
#     render_dimension_site.py. Editing the output makes it disagree with its generator and
#     `--check` fails. Their cards belong in the GENERATOR, and are added there.
def _withheld() -> set[str]:
    try:
        import json
        data = json.loads((ROOT / "withheld-routes.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return set()
    return {a["artifact"] for a in data.get("artifacts", [])}


# book/index.html is generated by build_book.py — a THIRD generator, found the same way
# as the first two: by breaking it. Any page produced by a build script belongs to that
# script, and its card goes in the script.
GENERATED = ({
                 "dimensions/index.html", "book/index.html", "offline/index.html",
                 "questions/index.html", "record/pqa-54/index.html",
             }
             | {f"{i}/index.html" for i in range(7)})
OPEN, CLOSE = "<!--OG:AUTO-->", "<!--/OG:AUTO-->"
CARD = "https://emergentism.org/assets/og/og-card.png"
SITE = "https://emergentism.org"

TITLE = re.compile(r"<title>(.*?)</title>", re.I | re.S)
DESC = re.compile(r'<meta\s+name="description"\s+content="(.*?)"', re.I | re.S)


def pages() -> list[Path]:
    out = []
    for dp, _dn, fn in os.walk(ROOT):
        rel = "/" + os.path.relpath(dp, ROOT).replace(os.sep, "/")
        if any(s in rel for s in SKIP):
            continue
        if "index.html" in fn:
            p = Path(dp) / "index.html"
            rel = str(p.relative_to(ROOT)).replace(os.sep, "/")
            if rel in GENERATED or rel in _withheld():
                continue
            out.append(p)
    return sorted(out)


def block(p: Path, text: str) -> str | None:
    if "og:image" in text and OPEN not in text:
        return None  # hand-authored; leave alone
    t = TITLE.search(text)
    d = DESC.search(text)
    if not t:
        return None
    title = html.unescape(re.sub(r"\s+", " ", t.group(1))).strip()
    desc = html.unescape(re.sub(r"\s+", " ", d.group(1))).strip() if d else ""
    route = "/" + str(p.parent.relative_to(ROOT)).replace(os.sep, "/").strip(".").strip("/")
    route = (route.rstrip("/") + "/") if route != "/" else "/"
    e = lambda s: html.escape(s, quote=True)
    return (
        f'{OPEN}\n'
        f'<meta property="og:type" content="website" />\n'
        f'<meta property="og:site_name" content="Emergentism" />\n'
        f'<meta property="og:title" content="{e(title)}" />\n'
        + (f'<meta property="og:description" content="{e(desc)}" />\n' if desc else "")
        + f'<meta property="og:url" content="{SITE}{route}" />\n'
        f'<meta property="og:image" content="{CARD}" />\n'
        f'<meta name="twitter:card" content="summary_large_image" />\n'
        f'<meta name="twitter:image" content="{CARD}" />\n'
        f'{CLOSE}'
    )


def main(argv: list[str]) -> int:
    check = "--check" in argv
    changed, skipped, noanchor, stale = 0, 0, [], []
    for p in pages():
        text = p.read_text(encoding="utf-8", errors="replace")
        b = block(p, text)
        if b is None:
            skipped += 1
            continue
        if OPEN in text and CLOSE in text:
            a, z = text.index(OPEN), text.index(CLOSE) + len(CLOSE)
            new = text[:a] + b + text[z:]
        elif "</head>" in text:
            i = text.index("</head>")
            new = text[:i] + b + "\n" + text[i:]
        else:
            noanchor.append(str(p.relative_to(ROOT)))
            continue
        if new != text:
            if check:
                stale.append(str(p.relative_to(ROOT)))
            else:
                p.write_text(new, encoding="utf-8")
                changed += 1

    if check:
        errs = []
        if stale:
            errs.append(f"{len(stale)} pages have stale or missing cards (e.g. {', '.join(stale[:3])})")
        if noanchor:
            errs.append(f"{len(noanchor)} pages have no </head>: {', '.join(noanchor[:3])}")
        if errs:
            print("SOCIAL CARDS: FAIL")
            for e in errs:
                print(f"- {e}")
            print("  fix: python3 -B build_social_cards.py")
            return 1
        print(f"SOCIAL CARDS: PASS (cards current; {skipped} pages left hand-authored)")
        return 0
    print(f"social cards: {changed} pages updated · {skipped} left hand-authored")
    if noanchor:
        print(f"  no </head>: {len(noanchor)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
