// Generated by build_pwa.py from release-manifest.json.
const CACHE = "emergentism-e3ac9f4009aa";
const PRECACHE = [
  "/",
  "/discoveries/",
  "/discoveries/degrees-of-freedom/",
  "/discoveries/reality-gradient/",
  "/discoveries/burrisphere/",
  "/discoveries/mass-shell/",
  "/discoveries/ladder/",
  "/discoveries/nonduality/",
  "/discoveries/game/",
  "/discoveries/paradoxes/",
  "/discoveries/universalizability/",
  "/discoveries/is-ought/",
  "/plainly/",
  "/practice/",
  "/record/",
  "/about/",
  "/offline/",
  "/manifest.webmanifest",
  "/assets/css/xai.css",
  "/assets/js/pwa.js",
  "/assets/icons/icon-192.png",
  "/assets/icons/icon-512.png"
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(
    keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))
  )));
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET' || new URL(event.request.url).origin !== location.origin) return;
  if (event.request.mode === 'navigate') {
    event.respondWith(fetch(event.request).then((response) => {
      const copy = response.clone();
      caches.open(CACHE).then((cache) => cache.put(event.request, copy));
      return response;
    }).catch(() => caches.match(event.request).then((hit) => hit || caches.match('/offline/'))));
    return;
  }
  event.respondWith(caches.match(event.request).then((hit) => hit || fetch(event.request)));
});
