#!/usr/bin/env python3
"""
compile_state.py — Auto-generate EMERGENTISM_ORG/11_UPLINK/09_STATE.md from live organism data.

Reads:
  - SKYZAI_ORG/P-SCORES.md (canonical health)
  - SKYZAI_ORG/02_ORGANS/*/  (file counts)
  - 03_VENTURES/*/ (file counts)
  - git status (if available)

Writes:
  - EMERGENTISM_ORG/11_UPLINK/09_STATE.md

Run: python3 EMERGENTISM_ORG/09_TOOLS/compile_state.py
"""

import os
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

# Paths relative to repo root
REPO_ROOT = Path(__file__).resolve().parent.parent.parent
P_SCORES_PATH = REPO_ROOT / "02_ORGANISM" / "P-SCORES.md"
ORGANS_DIR = REPO_ROOT / "02_ORGANISM" / "02_ORGANS"
ENTITIES_DIR = REPO_ROOT / "02_ORGANISM" / "01_ENTITIES"
OUTPUT_PATH = REPO_ROOT / "03_UPLINK" / "09_STATE.md"

# Known deployments (update as things go live)
DEPLOYMENTS = [
    ("API PAY", "Hedera mainnet", "Deployed, working", "Stablecoin payment settlement via OFN receipts"),
    ("aureus-pay SDK", "npm", "Published", "TypeScript SDK: npm i aureus-pay"),
    ("Connect G0 (sigil.ts)", "npm", "Shipped", "Nexus identity connection module"),
    ("Smart contracts", "Hedera testnet + mainnet", "Deployed", "PRISM, FlowWallet, LP100, Constitution, GraceExit"),
    ("APU G1", "Local/Cloud", "Fired", "First autonomous 8-Directorate Council deliberation"),
    ("Rosetta pipeline", "Local", "Operational", "L1-L7 chain + Cortex + K2 executor + Witnesses. ~20s/signal"),
    ("emergentism.org", "Vercel", "In deployment", "Framework website (59 TSX, 19 pages, 3D sims)"),
    ("OFN SDKs", "npm/PyPI", "Ready to publish", "Python, TypeScript, Dart, x402 adapter"),
]

BLOCKERS = [
    ("Circle backend not deployed", "TheCircle", "F1 signals don't flow", "Needs server + env vars"),
    ("ReFu MarketFactory traps funds", "RealityFutures", "Can't create markets safely", "Smart contract fix"),
    ("APU runs on mock data", "APU", "Recommendations are theoretical", "Wire Circle/ReFu feeds"),
    ("No continuous heartbeat", "Skyzai", "Organism doesn't breathe autonomously", "Schedule pipeline loop"),
    ("No upstream OSINT feeds", "TheCircle", "Brain has no eyes", "Connect World Monitor / news APIs"),
]


def count_files(directory: Path) -> int:
    """Count all files recursively."""
    if not directory.exists():
        return 0
    count = 0
    for root, dirs, files in os.walk(directory):
        count += len(files)
    return count


def extract_p_scores(p_scores_path: Path) -> list[dict]:
    """Extract organ P-scores from P-SCORES.md."""
    if not p_scores_path.exists():
        return []

    content = p_scores_path.read_text(encoding="utf-8")
    organs = []

    # Match organ table rows: | **Name** | Trivium | Phi | V | **P** | ...
    pattern = r'\|\s*\*\*(\w+(?:\.\w+)?)\*\*\s*\|\s*(\w+[^|]*)\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*\*\*([\d.]+)\*\*\s*\|\s*(\w+[^|]*)\|'
    for match in re.finditer(pattern, content):
        name, trivium, phi, v, p, classification = match.groups()
        organs.append({
            "name": name.strip(),
            "trivium": trivium.strip(),
            "phi": float(phi),
            "v": float(v),
            "p": float(p),
            "classification": classification.strip(),
        })

    return organs


def get_git_info() -> dict:
    """Get git status info."""
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", "-5"],
            capture_output=True, text=True, cwd=str(REPO_ROOT)
        )
        recent_commits = result.stdout.strip() if result.returncode == 0 else "No git history"

        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, cwd=str(REPO_ROOT)
        )
        head = result.stdout.strip() if result.returncode == 0 else "unknown"

        result = subprocess.run(
            ["git", "status", "--short"],
            capture_output=True, text=True, cwd=str(REPO_ROOT)
        )
        dirty_count = len(result.stdout.strip().split("\n")) if result.stdout.strip() else 0

        return {"head": head, "recent": recent_commits, "dirty": dirty_count}
    except FileNotFoundError:
        return {"head": "no git", "recent": "", "dirty": 0}


def generate_state() -> str:
    """Generate the 09_STATE.md content."""
    now = datetime.now(timezone.utc)
    organs = extract_p_scores(P_SCORES_PATH)
    git = get_git_info()

    lines = [
        f"# THE STATE — Organism Health Report",
        f"",
        f"> Auto-generated by `compile_state.py` on {now.strftime('%Y-%m-%d %H:%M UTC')}",
        f"> Source: `SKYZAI_ORG/P-SCORES.md` + file counts + git status",
        f"",
        f"---",
        f"",
        f"## P-Scores (from P-SCORES.md)",
        f"",
        f"| Organ | Trivium | P | Phi | V | Classification |",
        f"|-------|---------|---|-----|---|----------------|",
    ]

    for o in organs:
        lines.append(f"| **{o['name']}** | {o['trivium']} | {o['p']:.2f} | {o['phi']:.2f} | {o['v']:.2f} | {o['classification']} |")

    if organs:
        geo_mean = 1.0
        for o in organs:
            geo_mean *= o["p"]
        geo_mean = geo_mean ** (1.0 / len(organs))
        lines.append(f"| **Geometric Mean** | | **{geo_mean:.2f}** | | | |")

    lines.extend([
        f"",
        f"---",
        f"",
        f"## File Counts",
        f"",
        f"### Organs",
        f"",
    ])

    for organ_dir in sorted(ORGANS_DIR.iterdir()):
        if organ_dir.is_dir() and not organ_dir.name.startswith("."):
            count = count_files(organ_dir)
            lines.append(f"- **{organ_dir.name}:** {count:,} files")

    lines.extend(["", "### Entities", ""])

    for entity_dir in sorted(ENTITIES_DIR.iterdir()):
        if entity_dir.is_dir() and not entity_dir.name.startswith("."):
            count = count_files(entity_dir)
            lines.append(f"- **{entity_dir.name}:** {count:,} files")

    lines.extend([
        f"",
        f"---",
        f"",
        f"## What Is LIVE",
        f"",
        f"| Item | Platform | Status | What It Does |",
        f"|------|----------|--------|-------------|",
    ])

    for name, platform, status, desc in DEPLOYMENTS:
        lines.append(f"| **{name}** | {platform} | {status} | {desc} |")

    lines.extend([
        f"",
        f"---",
        f"",
        f"## Blockers",
        f"",
        f"| Blocker | Organ | Impact | Resolution |",
        f"|---------|-------|--------|------------|",
    ])

    for blocker, organ, impact, resolution in BLOCKERS:
        lines.append(f"| {blocker} | {organ} | {impact} | {resolution} |")

    lines.extend([
        f"",
        f"---",
        f"",
        f"## Repository",
        f"",
        f"- **Git HEAD:** {git['head']}",
        f"- **Uncommitted changes:** {git['dirty']}",
        f"- **Recent commits:**",
        f"```",
        git["recent"],
        f"```",
        f"",
        f"---",
        f"",
        f"*Compiled: {now.strftime('%Y-%m-%d %H:%M UTC')}*",
    ])

    return "\n".join(lines)


def main():
    content = generate_state()
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"[compile_state] Written to {OUTPUT_PATH}")
    print(f"[compile_state] {len(content)} bytes")


if __name__ == "__main__":
    main()
