#!/usr/bin/env python3
"""The frozen corpus for M4-01: the complete space of strictly ordinal 2x2 games.

WHY THIS CORPUS
---------------
`08_M4_COMPRESSION_PROTOCOL_v0.1.md` §5 lists a kill: "the corpus was selected
using the desired placements or results." The only corpus immune to that kill is
a COMPLETE ENUMERATION -- there is no sampling rule to bias, because nothing is
sampled. This module generates the entire space and nothing else.

CONSTRUCTION (stated exactly, so the hash is reproducible from the definition)
-----------------------------------------------------------------------------
Two players. Row chooses T or B; Column chooses L or R. Four outcome cells:
(T,L), (T,R), (B,L), (B,R). Each player holds a STRICT ordinal preference over
the four cells, written as ranks 1..4 where 4 is best. Each player therefore has
4! = 24 rankings, giving 24 * 24 = 576 ordered pairs.

That 576 is the raw space. Games are then reduced under the relabelling group
generated by:

  * swapping Row's two strategy labels   (T <-> B)
  * swapping Column's two strategy labels (L <-> R)
  * exchanging the two player roles      (transpose the matrix and swap whose
    ranks are whose)

That group has order 8. A game's canonical form is the lexicographically
smallest of its up-to-8 images; the corpus holds one representative per orbit.
The resulting count is REPORTED, never asserted in advance -- this module prints
what it finds and the hash covers exactly that.

The standard literature on this space is Rapoport & Guyer (1966) and Robinson &
Goforth, *The Topology of the 2x2 Games* (2005). They are cited as the reason
the space is a recognised external object, NOT as authority for the count this
file computes: a count here is whatever the stated group yields, and the reader
can re-run it.

GROUND TRUTH
------------
Every label below is computed from the payoff ranks alone, by definition, with
no model and no interpretation:

  * `pure_ne_count`  -- number of pure-strategy Nash equilibria (a cell where
    neither player can improve its own rank by a unilateral deviation)
  * `row_dominant`   -- Row has a strategy better in both Column-columns
  * `col_dominant`   -- Column likewise
  * `nash_pareto`    -- at least one pure NE is Pareto-efficient
  * `is_dilemma`     -- a pure NE exists and every pure NE is Pareto-dominated
    by some other cell (the Prisoner's-Dilemma shape, stated structurally)

Usage:
    python3 -B game_corpus.py [--out corpus.json]
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
from pathlib import Path

CELLS = ((0, 0), (0, 1), (1, 0), (1, 1))  # (row_strategy, col_strategy)


def rankings():
    """All 24 strict rankings of four cells, as a tuple indexed by cell order."""
    return list(itertools.permutations((1, 2, 3, 4)))


def as_matrix(row_rank, col_rank):
    """((r,c) at TL, TR, BL, BR) -> nested tuple m[row][col] = (row_rank, col_rank)."""
    flat = tuple(zip(row_rank, col_rank))
    return ((flat[0], flat[1]), (flat[2], flat[3]))


def flatten(matrix):
    return (matrix[0][0], matrix[0][1], matrix[1][0], matrix[1][1])


def swap_rows(m):
    return (m[1], m[0])


def swap_cols(m):
    return ((m[0][1], m[0][0]), (m[1][1], m[1][0]))


def transpose_roles(m):
    """Exchange the two players: transpose the grid and swap each pair."""
    return (
        ((m[0][0][1], m[0][0][0]), (m[1][0][1], m[1][0][0])),
        ((m[0][1][1], m[0][1][0]), (m[1][1][1], m[1][1][0])),
    )


def orbit(m):
    """All images of m under the order-8 relabelling group."""
    seen = set()
    frontier = [m]
    while frontier:
        cur = frontier.pop()
        key = flatten(cur)
        if key in seen:
            continue
        seen.add(key)
        frontier.extend((swap_rows(cur), swap_cols(cur), transpose_roles(cur)))
    return seen


def canonical(m):
    return min(orbit(m))


def pure_nash(m):
    """Cells where neither player gains by deviating alone. Ranks: higher is better."""
    out = []
    for r, c in CELLS:
        row_here, col_here = m[r][c]
        if m[1 - r][c][0] > row_here:
            continue
        if m[r][1 - c][1] > col_here:
            continue
        out.append((r, c))
    return out


def dominant(m, player):
    """Does `player` (0=row, 1=col) hold a strategy better against every opponent move?"""
    for mine in (0, 1):
        other = 1 - mine
        if player == 0:
            better = all(m[mine][c][0] > m[other][c][0] for c in (0, 1))
        else:
            better = all(m[r][mine][1] > m[r][other][1] for r in (0, 1))
        if better:
            return True
    return False


def pareto_dominated(m, cell):
    """Some other cell is at least as good for both and strictly better for one."""
    r, c = cell
    mine = m[r][c]
    for rr, cc in CELLS:
        if (rr, cc) == cell:
            continue
        other = m[rr][cc]
        if other[0] >= mine[0] and other[1] >= mine[1] and other != mine:
            return True
    return False


def describe(m):
    ne = pure_nash(m)
    return {
        "matrix": [[list(m[r][c]) for c in (0, 1)] for r in (0, 1)],
        "pure_ne_count": len(ne),
        "pure_ne_cells": [list(x) for x in ne],
        "row_dominant": dominant(m, 0),
        "col_dominant": dominant(m, 1),
        "nash_pareto": any(not pareto_dominated(m, cell) for cell in ne),
        "is_dilemma": bool(ne) and all(pareto_dominated(m, cell) for cell in ne),
    }


def build():
    perms = rankings()
    raw = 0
    reps = {}
    for row_rank in perms:
        for col_rank in perms:
            raw += 1
            m = as_matrix(row_rank, col_rank)
            key = canonical(m)
            if key not in reps:
                reps[key] = ((key[0], key[1]), (key[2], key[3]))

    games = []
    for idx, key in enumerate(sorted(reps)):
        m = reps[key]
        row = describe(m)
        row["id"] = f"G{idx:03d}"
        games.append(row)
    return raw, games


def corpus_sha(games) -> str:
    payload = json.dumps(games, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(payload).hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).with_name("corpus_2x2_ordinal.json"))
    args = ap.parse_args()

    raw, games = build()
    sha = corpus_sha(games)
    doc = {
        "id": "ORDINAL_2X2_COMPLETE",
        "version": "v1",
        "sha256": sha,
        "raw_ordered_pairs": raw,
        "equivalence": "order-8 relabelling group: swap row labels, swap column labels, exchange player roles",
        "count": len(games),
        "sampling_rule": "none — complete enumeration of the space, then one representative per orbit",
        "exclusions": "none",
        "citation": "Rapoport & Guyer (1966); Robinson & Goforth, The Topology of the 2x2 Games (2005) — cited as the external provenance of the space, not as authority for this count",
        "games": games,
    }
    args.out.write_text(json.dumps(doc, indent=1), encoding="utf-8")

    from collections import Counter
    print(f"raw ordered pairs (24 x 24)   {raw}")
    print(f"orbits under the order-8 group {len(games)}")
    print(f"corpus sha256                  {sha}")
    print("\nground-truth label balance (pure_ne_count):")
    for k, v in sorted(Counter(g["pure_ne_count"] for g in games).items()):
        print(f"  {k} equilibria   {v:4d}")
    print(f"\ndilemma-shaped games           {sum(g['is_dilemma'] for g in games)}")
    print(f"written: {args.out.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
