#!/usr/bin/env python3
# rosetta:
#   primary_level: L3
#   primary_column: Meta
#   operator: "Kṛṣṇa ◇"
#   tier: "Executive"
#   regime: "Vaiśya"
#   register: "[S]"
#   canonical_phrase: "Canonical register builder — deterministic Git-index inventory"
# type: tool
# title: build_magnum_opus_register.py — FILE/FOLDER register generator + drift checker
# status: "ACTIVE 2026-07-20 — Git-index deterministic"
# owner: 01_EMERGENTISM
"""Build or check the two live Magnum Opus inventory registers.

Only these live artifacts are generated:

* ``00_META/registers/FILE_REGISTER.json``
* ``00_META/registers/FOLDER_REGISTER.json``

The dated 03/04 evidence artifacts and 05/06 disposition manifests are inputs or
historical records; this program never rewrites them.  All semantic input comes
from the Git *index*: paths from ``git ls-files -s -z`` and bytes from
``git cat-file --batch``.  Working-tree bytes cannot silently enter a register.

``--write`` is intentionally fail-closed.  Every non-register change must first
be staged, so the generated bytes describe one reviewable index snapshot.
Register outputs themselves may be dirty because writing them is this command's
purpose.  ``--check`` compares that same index-derived snapshot with the two
working-tree JSON outputs.

Determinism contract: sorted paths, canonical JSON formatting, no timestamps,
and exactly one stable ``SELF`` row for FILE_REGISTER.json.
"""

import argparse
import csv
import hashlib
import io
import json
import os
import re
import subprocess
import sys
from collections import Counter
from dataclasses import dataclass


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REG_DIR_REL = "00_META/registers"
FILE_REG_REL = REG_DIR_REL + "/FILE_REGISTER.json"
FOLDER_REG_REL = REG_DIR_REL + "/FOLDER_REGISTER.json"
SELF_PATH = FILE_REG_REL
GENERATED_REGISTER_PATHS = frozenset((FILE_REG_REL, FOLDER_REG_REL))
REF_CAP = 999
FM_READ_BYTES = 16384

# Historical disposition inputs are provenance, never active canon.
FILE_MANIFEST_REL = "90_ARCHIVE/pure_emergentism_boundary_2026_07_20/00_META/05_MAGNUM_OPUS_FILE_DISPOSITION_MANIFEST_PENDING_SIGNATURE_2026_07_19.csv"
FOLDER_MANIFEST_REL = "90_ARCHIVE/pure_emergentism_boundary_2026_07_20/00_META/06_MAGNUM_OPUS_FOLDER_DISPOSITION_MANIFEST_PENDING_SIGNATURE_2026_07_19.csv"

# Kernel surfaces.  These mappings classify the index; they do not create canon.
K_EXACT = {
    "05_COSMOLOGY/00_CANONICAL_FORMULA_BLOCK.md": "K-1",
    "05_COSMOLOGY/01_THE_TRANSCENDENTAL_TRINITY/41_THE_GLYPH_TRANSFORMATIONS.md": "K-1",
    "06_ONTOLOGY/02_THE_DEGREES_OF_FREEDOM_ONTOLOGY.md": "K-2",
    "06_ONTOLOGY/00_WELTANSCHAUUNG_KERNEL_v0.2_EMERGENTISM_ONLY.md": "K-2",
    "06_ONTOLOGY/03_THE_EMERGENT_AXIOMS.md": "K-3",
    "06_ONTOLOGY/04_THE_CONJECTURES.md": "K-4",
    "00_META/00_THE_FIVE_PLUS_ONE_CONSTITUTION.md": "K-5",
    "06_ONTOLOGY/06_THE_REVELATIONS.md": "K-6",
    "02_EPISTEMOLOGY/00_THE_SYNTHETIC_GAP_AND_FOUR_POSTURES_v0.1.md": "K-7",
}
K_PREFIX = (
    ("11_UPLINK/50_AUDITS_AND_EXECUTIONS/", "K-7"),
    ("12_PUBLIC_SITE/record/", "K-7"),
)

TIER_RE = re.compile(r"\[(S|I|C|D|B|A)\]")
TOKEN_RE = re.compile(r"[\w.\-]+", re.UNICODE)
CORPUS_EXTS = (".md", ".html")
CONFIG_NAMES = {".gitignore", ".gitattributes", ".gitmodules", "license", "makefile"}
CONFIG_EXTS = {".json", ".yaml", ".yml", ".toml", ".cfg", ".ini", ".lock"}


class RegisterError(RuntimeError):
    """The requested register snapshot is ambiguous or unsafe."""


@dataclass(frozen=True)
class IndexEntry:
    mode: str
    oid: str
    path: str


def _git(repo_root, *args, input_bytes=None):
    return subprocess.run(
        ["git", "-C", repo_root, *args],
        input=input_bytes,
        check=True,
        capture_output=True,
    ).stdout


def parse_index_records(raw):
    """Parse ``git ls-files -s -z`` and reject conflicts or duplicate paths."""
    entries = []
    seen = set()
    for record in raw.split(b"\0"):
        if not record:
            continue
        meta, separator, encoded_path = record.partition(b"\t")
        fields = meta.split()
        if not separator or len(fields) != 3:
            raise RegisterError("malformed git ls-files -s -z record")
        mode = fields[0].decode("ascii", "strict")
        oid = fields[1].decode("ascii", "strict")
        stage = fields[2].decode("ascii", "strict")
        path = encoded_path.decode("utf-8", "surrogateescape")
        if stage != "0":
            raise RegisterError(f"unmerged index entry at stage {stage}: {path}")
        if path in seen:
            raise RegisterError(f"duplicate path in Git index: {path}")
        seen.add(path)
        entries.append(IndexEntry(mode=mode, oid=oid, path=path))
    return sorted(entries, key=lambda entry: entry.path)


def git_index_entries(repo_root=REPO_ROOT):
    return parse_index_records(_git(repo_root, "ls-files", "-s", "-z"))


def parse_cat_file_batch(raw, requested_oids):
    """Parse ``git cat-file --batch`` output for an ordered list of object IDs."""
    cursor = 0
    by_oid = {}
    for requested in requested_oids:
        line_end = raw.find(b"\n", cursor)
        if line_end < 0:
            raise RegisterError(f"truncated git cat-file header for {requested}")
        header = raw[cursor:line_end].decode("ascii", "strict").split()
        cursor = line_end + 1
        if len(header) == 2 and header[1] == "missing":
            raise RegisterError(f"missing indexed object: {requested}")
        if len(header) != 3:
            raise RegisterError(f"malformed git cat-file header for {requested}")
        returned_oid, object_type, size_text = header
        if returned_oid != requested:
            raise RegisterError(
                f"git cat-file returned {returned_oid} while {requested} was requested"
            )
        if object_type != "blob":
            raise RegisterError(
                f"indexed path resolves to {object_type}, not blob: {requested}"
            )
        try:
            size = int(size_text)
        except ValueError as exc:
            raise RegisterError(f"invalid blob size for {requested}") from exc
        end = cursor + size
        if end > len(raw) or raw[end:end + 1] != b"\n":
            raise RegisterError(f"truncated git cat-file payload for {requested}")
        by_oid[requested] = raw[cursor:end]
        cursor = end + 1
    if cursor != len(raw):
        raise RegisterError("unexpected trailing bytes from git cat-file --batch")
    return by_oid


def git_index_blobs(entries, repo_root=REPO_ROOT):
    """Return ``path -> exact index blob bytes`` using one batched Git read."""
    requested_oids = list(dict.fromkeys(entry.oid for entry in entries))
    if not requested_oids:
        return {}
    request = b"".join(oid.encode("ascii") + b"\n" for oid in requested_oids)
    raw = _git(repo_root, "cat-file", "--batch", input_bytes=request)
    by_oid = parse_cat_file_batch(raw, requested_oids)
    return {entry.path: by_oid[entry.oid] for entry in entries}


def index_snapshot(repo_root=REPO_ROOT):
    entries = git_index_entries(repo_root)
    blobs = git_index_blobs(entries, repo_root)
    if len(blobs) != len(entries):
        raise RegisterError("Git-index snapshot lost or duplicated a tracked path")
    return entries, blobs


def sha256_bytes(raw):
    return hashlib.sha256(raw).hexdigest()


def read_frontmatter(raw):
    """Cheap first-block YAML scan from immutable index bytes."""
    text = raw[:FM_READ_BYTES].decode("utf-8", "replace")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    block = []
    for line in lines[1:]:
        if line.strip() == "---":
            break
        block.append(line)
    else:
        return {}
    fields = {}
    for line in block:
        match = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if match:
            value = match.group(2).strip().strip('"').strip("'")
            fields.setdefault(match.group(1), value)
    return fields


def authority_from_status(status):
    if not status:
        return "unrated"
    upper = status.upper()
    if any(token in upper for token in ("STAGED", "PENDING", "[D]", "DRAFT")):
        return "staged"
    if "SIGNED" in upper:
        return "signed"
    return "unrated"


def evidence_tier_from(fields):
    value = fields.get("evidence_tier")
    if not value:
        return None
    match = TIER_RE.search(value)
    return match.group(0) if match else None


def artifact_class(path):
    top = path.split("/", 1)[0]
    if top in ("90_ARCHIVE", "91_COMPATIBILITY"):
        return "archive"
    if top == "12_PUBLIC_SITE":
        return "site"
    if top == "09_TOOLS":
        return "tool"
    base = path.rsplit("/", 1)[-1]
    low = base.lower()
    stem, extension = os.path.splitext(low)
    if "receipt" in low or "50_audits_and_executions" in path.lower():
        return "receipt"
    if low in CONFIG_NAMES or stem in CONFIG_NAMES or extension in CONFIG_EXTS:
        return "config"
    if extension in (".md", ".markdown"):
        return "doctrine"
    return "other"


def k_relation(path):
    if path in K_EXACT:
        return K_EXACT[path]
    for prefix, relation in K_PREFIX:
        if path.startswith(prefix):
            return relation
    return None


def map_disposition(raw):
    upper = (raw or "").upper()
    if not upper:
        return "keep"
    if any(token in upper for token in ("ARCHIVE", "TOMBSTONE", "STONE")):
        return "tombstone-candidate"
    if any(token in upper for token in ("ABSORB", "REVISE", "STAGED", "ROUTE", "SUCCESSION")):
        return "staged"
    return "keep"


def load_manifest_dispositions(raw, key_col):
    table = {}
    if not raw:
        return table
    text = raw.decode("utf-8", "replace")
    for row in csv.DictReader(io.StringIO(text)):
        key = (row.get(key_col) or "").strip()
        if key:
            table[key] = map_disposition(row.get("disposition"))
    return table


def build_ref_index(tracked, blobs):
    """Return basename hit counts from tracked Markdown/HTML index blobs."""
    basenames = {path.rsplit("/", 1)[-1] for path in tracked}
    counts = Counter()
    for path in tracked:
        if not path.lower().endswith(CORPUS_EXTS):
            continue
        text = blobs[path].decode("utf-8", "replace")
        for token, count in Counter(TOKEN_RE.findall(text)).items():
            if token in basenames:
                counts[token] += count
    return counts


def self_entry():
    return {
        "path": SELF_PATH,
        "sha256": "SELF",
        "bytes": 0,
        "owner_lane": "00_META",
        "artifact_class": "config",
        "authority_status": "unrated",
        "evidence_tier": None,
        "k_relation": None,
        "public_projection": None,
        "disposition": "keep",
        "destination": None,
        "absorber": None,
        "inbound_references": 0,
        "gate": None,
        "review_state": "unreviewed",
    }


def file_entry(path, raw, ref_counts, manifest_disp):
    fields = read_frontmatter(raw) if path.lower().endswith((".md", ".markdown")) else {}
    base = path.rsplit("/", 1)[-1]
    top = path.split("/", 1)[0]
    return {
        "path": path,
        "sha256": sha256_bytes(raw),
        "bytes": len(raw),
        "owner_lane": top if "/" in path else "root",
        "artifact_class": artifact_class(path),
        "authority_status": authority_from_status(fields.get("status")),
        "evidence_tier": evidence_tier_from(fields),
        "k_relation": k_relation(path),
        "public_projection": path if path.startswith("12_PUBLIC_SITE/") else None,
        "disposition": manifest_disp.get(path, "keep"),
        "destination": None,
        "absorber": None,
        "inbound_references": min(ref_counts.get(base, 0), REF_CAP),
        "gate": None,
        "review_state": "unreviewed",
    }


def folder_type(path):
    if path == ".":
        return "other"
    top = path.split("/", 1)[0]
    if top in ("00_META", "00_CONTROL"):
        return "meta"
    if top in ("90_ARCHIVE", "91_COMPATIBILITY"):
        return "archive"
    if top == "12_PUBLIC_SITE":
        return "site"
    if top == "09_TOOLS":
        return "tool"
    if top == "10_SEED":
        return "seed"
    if re.match(r"^(0[1-8]|11)_", top):
        return "lane"
    return "other"


def folder_scope_guess(raw):
    """Derive one scope line from front-door index bytes."""
    if raw is None:
        return None
    fields = read_frontmatter(raw)
    for key in ("canonical_phrase", "title", "description"):
        value = fields.get(key)
        if value:
            return value[:140]
    in_frontmatter = False
    for line in raw[:FM_READ_BYTES].decode("utf-8", "replace").splitlines():
        stripped = line.strip()
        if stripped == "---":
            in_frontmatter = not in_frontmatter
            continue
        if in_frontmatter or not stripped or stripped.startswith("#") or stripped.startswith("<!--"):
            continue
        return stripped[:140]
    return None


def build_folder_entries(tracked, blobs, manifest_disp):
    parents = {}
    for path in tracked:
        directory = path.rsplit("/", 1)[0] if "/" in path else "."
        parts = directory.split("/") if directory != "." else ["."]
        for index in range(len(parts)):
            parents.setdefault("/".join(parts[:index + 1]), 0)
        parents[directory] += 1
    file_set = set(tracked)
    entries = []
    for folder in sorted(parents):
        prefix = "" if folder == "." else folder + "/"
        door = next(
            (prefix + name for name in ("README.md", "AGENTS.md", "index.html")
             if prefix + name in file_set),
            None,
        )
        door_raw = blobs.get(door) if door else None
        door_fields = read_frontmatter(door_raw) if door and door.lower().endswith(".md") else {}
        count = sum(1 for path in tracked if path.startswith(prefix)) if prefix else len(tracked)
        entries.append({
            "path": folder,
            "type": folder_type(folder),
            "nearest_front_door": door,
            "front_door_requirement": "present" if door else "missing",
            "owns": folder_scope_guess(door_raw),
            "must_not_own": None,
            "status": authority_from_status(door_fields.get("status")),
            "tracked_file_count": count,
            "disposition": manifest_disp.get(folder, "keep"),
            "gate": None,
            "review_state": "unreviewed",
        })
    return entries


def validate_register(doc, label):
    entries = doc.get("entries")
    if not isinstance(entries, list):
        raise RegisterError(f"{label}: entries must be a list")
    if doc.get("entry_count") != len(entries):
        raise RegisterError(
            f"{label}: entry_count {doc.get('entry_count')!r} != {len(entries)}"
        )
    paths = [entry.get("path") for entry in entries]
    if any(not isinstance(path, str) for path in paths):
        raise RegisterError(f"{label}: every entry requires a string path")
    if len(paths) != len(set(paths)):
        raise RegisterError(f"{label}: duplicate entry paths")
    if paths != sorted(paths):
        raise RegisterError(f"{label}: entries are not sorted by path")


def derive(repo_root=REPO_ROOT, snapshot=None):
    if snapshot is None:
        index_entries, blobs = index_snapshot(repo_root)
    else:
        index_entries, blobs = snapshot
    tracked = [entry.path for entry in index_entries]
    if len(tracked) != len(set(tracked)) or set(tracked) != set(blobs):
        raise RegisterError("invalid Git-index snapshot: paths are not one-to-one")
    if SELF_PATH not in blobs:
        raise RegisterError(f"tracked self register is required: {SELF_PATH}")

    file_disp = load_manifest_dispositions(blobs.get(FILE_MANIFEST_REL, b""), "path")
    folder_disp = load_manifest_dispositions(blobs.get(FOLDER_MANIFEST_REL, b""), "folder")
    ref_counts = build_ref_index(tracked, blobs)
    file_entries = [
        self_entry() if path == SELF_PATH
        else file_entry(path, blobs[path], ref_counts, file_disp)
        for path in tracked
    ]
    file_entries.sort(key=lambda entry: entry["path"])
    folder_entries = build_folder_entries(tracked, blobs, folder_disp)
    file_doc = {
        "schema": "magnum-opus/file-register/v1",
        "generator": "09_TOOLS/01_SCRIPTS/build_magnum_opus_register.py",
        "source": "Git index paths and blob bytes (deterministic; no timestamps)",
        "entry_count": len(file_entries),
        "entries": file_entries,
    }
    folder_doc = {
        "schema": "magnum-opus/folder-register/v1",
        "generator": "09_TOOLS/01_SCRIPTS/build_magnum_opus_register.py",
        "source": "Git index directory closure and blob bytes (deterministic; no timestamps)",
        "entry_count": len(folder_entries),
        "entries": folder_entries,
    }
    validate_register(file_doc, FILE_REG_REL)
    validate_register(folder_doc, FOLDER_REG_REL)
    return file_doc, folder_doc


def _decode_z_paths(raw):
    return [
        item.decode("utf-8", "surrogateescape")
        for item in raw.split(b"\0")
        if item
    ]


def is_register_output(path):
    return path in GENERATED_REGISTER_PATHS


def assert_write_safe(repo_root=REPO_ROOT):
    """Require every non-generated change to be represented in the Git index."""
    unstaged = _decode_z_paths(_git(repo_root, "diff", "--name-only", "-z"))
    untracked = _decode_z_paths(
        _git(repo_root, "ls-files", "--others", "--exclude-standard", "-z")
    )
    unsafe = sorted({path for path in unstaged + untracked if not is_register_output(path)})
    if unsafe:
        preview = "\n  ".join(unsafe[:25])
        suffix = "\n  ..." if len(unsafe) > 25 else ""
        raise RegisterError(
            "--write requires all non-register changes staged; unresolved paths:\n  "
            + preview + suffix
        )


def serialized(doc):
    return (json.dumps(doc, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def dump(doc, abs_path):
    with open(abs_path, "wb") as handle:
        handle.write(serialized(doc))


def write_registers(file_doc, folder_doc, repo_root=REPO_ROOT):
    """Write only the two undated live registers."""
    validate_register(file_doc, FILE_REG_REL)
    validate_register(folder_doc, FOLDER_REG_REL)
    register_dir = os.path.join(repo_root, REG_DIR_REL)
    os.makedirs(register_dir, exist_ok=True)
    dump(file_doc, os.path.join(repo_root, FILE_REG_REL))
    dump(folder_doc, os.path.join(repo_root, FOLDER_REG_REL))


def diff_docs(derived, on_disk):
    validate_register(derived, "derived register")
    validate_register(on_disk, "on-disk register")
    derived_entries = {entry["path"]: entry for entry in derived["entries"]}
    disk_entries = {entry["path"]: entry for entry in on_disk["entries"]}
    added = sorted(set(derived_entries) - set(disk_entries))
    removed = sorted(set(disk_entries) - set(derived_entries))
    changed = []
    metadata_keys = sorted((set(derived) | set(on_disk)) - {"entries"})
    metadata_changes = [
        key for key in metadata_keys if derived.get(key) != on_disk.get(key)
    ]
    if metadata_changes:
        changed.append(("<register metadata>", metadata_changes[:4]))
    for path in sorted(set(derived_entries) & set(disk_entries)):
        if derived_entries[path] != disk_entries[path]:
            fields = [
                key for key in derived_entries[path]
                if derived_entries[path].get(key) != disk_entries[path].get(key)
            ]
            changed.append((path, fields[:4]))
    return added, removed, changed


def main(argv=None):
    parser = argparse.ArgumentParser(description="Build/check deterministic Git-index registers.")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="generate FILE_REGISTER.json + FOLDER_REGISTER.json")
    mode.add_argument("--check", action="store_true", help="report drift against the Git-index snapshot")
    args = parser.parse_args(argv)

    try:
        if args.write:
            assert_write_safe(REPO_ROOT)
        file_doc, folder_doc = derive(REPO_ROOT)

        if args.write:
            write_registers(file_doc, folder_doc, REPO_ROOT)
            print(f"wrote {FILE_REG_REL} ({file_doc['entry_count']} entries)")
            print(f"wrote {FOLDER_REG_REL} ({folder_doc['entry_count']} entries)")
            return 0

        drift = False
        for relative, derived_doc in (
            (FILE_REG_REL, file_doc),
            (FOLDER_REG_REL, folder_doc),
        ):
            absolute = os.path.join(REPO_ROOT, relative)
            try:
                with open(absolute, encoding="utf-8") as handle:
                    on_disk = json.load(handle)
                added, removed, changed = diff_docs(derived_doc, on_disk)
            except (OSError, json.JSONDecodeError, RegisterError) as exc:
                print(f"DRIFT {relative}: invalid or unreadable on disk ({exc})")
                drift = True
                continue
            if added or removed or changed:
                drift = True
                print(
                    f"DRIFT {relative}: +{len(added)} added, "
                    f"-{len(removed)} removed, ~{len(changed)} changed"
                )
                for path in added[:25]:
                    print(f"  added   {path}")
                for path in removed[:25]:
                    print(f"  removed {path}")
                for path, fields in changed[:25]:
                    print(f"  changed {path} ({', '.join(fields)})")
            else:
                print(f"clean {relative} ({derived_doc['entry_count']} entries)")
        return 1 if drift else 0
    except (RegisterError, subprocess.CalledProcessError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
