#!/usr/bin/env python3
# rosetta:
#   primary_level: L3
#   primary_column: Meta
#   operator: "Kṛṣṇa ◇"
#   tier: "Executive"
#   regime: "Vaiśya"
#   register: "[S]"
#   canonical_phrase: "Canonical register builder — completion plan §2, additive-only"
# type: tool
# title: build_magnum_opus_register.py — FILE/FOLDER register generator + drift checker
# status: "ACTIVE 2026-07-19 — additive-only remediation wave (receipt 141A gate)"
# owner: 01_EMERGENTISM
"""Build the Magnum Opus canonical registers (completion plan §2).

Outputs (under 00_META/registers/):
  FILE_REGISTER.json   — one entry per TRACKED file (git ls-files, working tree)
  FOLDER_REGISTER.json — one entry per populated tracked directory
  README.md            — exact generated custody note (constant content)

Modes:
  --write  generate both registers and restore the exact README.md
  --check  re-derive both registers and report drift;
           exit 1 on drift (changed/added/removed paths listed), exit 0 when clean

Deterministic: entries sorted by path; no timestamps; no HEAD hash.
Evidence tiers: [S] disk-read, [I] inference. Additive-only: this script never
moves, deletes, tombstones, or commits anything.

Derivation notes:
  * authority_status: frontmatter `status` (cheap first-block YAML scan) —
    STAGED/PENDING/[D]/DRAFT -> 'staged'; an explicit leading signed status ->
    'signed'; mentions, denials, forwarding stubs, and disputed/superseded
    provenance remain 'unrated'.
  * evidence_tier: first [S]/[I]/[C]/[D]/[B]/[A] token in frontmatter
    `evidence_tier`, else null (spec: frontmatter evidence_tier else null).
  * k_relation: named kernel surfaces per
    00_META/00_THE_MAGNUM_OPUS_BLUEPRINT_PENDING_SIGNATURE.md §1.0 — exact file
    matches for K-1..K-6; K-7 = prefix surfaces 11_UPLINK/50_AUDITS_AND_EXECUTIONS/
    + 12_PUBLIC_SITE/record/ + the SYNTHETIC_GAP postures source (canonical path).
  * inbound_references: single-pass count of exact-basename token hits across all
    tracked .md/.html files (self-included, per spec's "grep hits for the
    basename"), capped at 999. Token-based; basenames with non-word characters
    (e.g. U+00D7) may undercount — documented approximation of git grep -o.
  * disposition: from 00_META/05/06 disposition manifests (current docs) —
    ARCHIVE/TOMBSTONE/STONE -> 'tombstone-candidate';
    ABSORB/REVISE/STAGED/ROUTE/SUCCESSION -> 'staged'; else 'keep'.
  * FILE_REGISTER and FOLDER_REGISTER use stable SELF markers because hashing
    either generated register into FILE_REGISTER would make a one-pass rebuild
    depend on the previous generated bytes. Other register-family files,
    including README.md, carry their real byte hashes.
  * A non-output path still present in `git ls-files` but absent from the working
    tree is a hard custody failure in both modes. `--write` returns nonzero
    before writing anything; it never normalizes missing source bytes into a
    generated register. The three declared outputs are the sole reconstruction
    exception in write mode.
"""

import argparse
import csv
import hashlib
import json
import os
import re
import subprocess
import sys
from collections import Counter

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REG_DIR_REL = "00_META/registers"
REG_DIR = os.path.join(REPO_ROOT, REG_DIR_REL)
FILE_REG_REL = REG_DIR_REL + "/FILE_REGISTER.json"
FOLDER_REG_REL = REG_DIR_REL + "/FOLDER_REGISTER.json"
README_REL = REG_DIR_REL + "/README.md"
REGISTER_GENERATOR = "09_TOOLS/01_SCRIPTS/build_magnum_opus_register.py"
FILE_SCHEMA = "magnum-opus/file-register/v1"
FOLDER_SCHEMA = "magnum-opus/folder-register/v1"
FILE_SOURCE = "git ls-files + working-tree bytes (deterministic; no timestamps)"
FOLDER_SOURCE = "git ls-files directory closure (deterministic; no timestamps)"
CYCLIC_REGISTER_PATHS = frozenset((FILE_REG_REL, FOLDER_REG_REL))
GENERATED_OUTPUT_PATHS = frozenset((FILE_REG_REL, FOLDER_REG_REL, README_REL))
DOCUMENT_KEYS = frozenset(("schema", "generator", "source", "entry_count", "entries"))
REF_CAP = 999
FM_READ_BYTES = 16384

FILE_MANIFEST = os.path.join(REPO_ROOT, "00_META", "05_MAGNUM_OPUS_FILE_DISPOSITION_MANIFEST_PENDING_SIGNATURE_2026_07_19.csv")
FOLDER_MANIFEST = os.path.join(REPO_ROOT, "00_META", "06_MAGNUM_OPUS_FOLDER_DISPOSITION_MANIFEST_PENDING_SIGNATURE_2026_07_19.csv")

# Blueprint §1.0 named kernel surfaces (verified on disk 2026-07-19 [S]).
K_EXACT = {
    "05_COSMOLOGY/00_CANONICAL_FORMULA_BLOCK.md": "K-1",
    "05_COSMOLOGY/01_THE_TRANSCENDENTAL_TRINITY/41_THE_GLYPH_TRANSFORMATIONS.md": "K-1",
    "06_ONTOLOGY/02_THE_DEGREES_OF_FREEDOM_ONTOLOGY.md": "K-2",
    "06_ONTOLOGY/00_WELTANSCHAUUNG_KERNEL_v0.2_EMERGENTISM_ONLY.md": "K-2",
    "06_ONTOLOGY/03_THE_EMERGENT_AXIOMS.md": "K-3",
    "06_ONTOLOGY/04_THE_CONJECTURES.md": "K-4",
    "00_META/00_THE_FIVE_PLUS_ONE_CONSTITUTION.md": "K-5",
    "06_ONTOLOGY/06_THE_REVELATIONS.md": "K-6",
    "02_EPISTEMOLOGY/00_THE_SYNTHETIC_GAP_AND_FOUR_POSTURES_v0.1.md": "K-7",
}
K_PREFIX = (
    ("11_UPLINK/50_AUDITS_AND_EXECUTIONS/", "K-7"),
    ("12_PUBLIC_SITE/record/", "K-7"),
)

TIER_RE = re.compile(r"\[(S|I|C|D|B|A)\]")
SIGNED_STATUS_RE = re.compile(
    r"^(?:SIGNED\b|\[E\]\s+[A-Z0-9][A-Z0-9_-]*-(?:COUNTERSIGNED|SHIP-SIGNED)\b|"
    r"[A-Z0-9][A-Z0-9_-]*-(?:COUNTERSIGNED|SHIP-SIGNED)\b|"
    r"ACTIVE(?:\s+RECEIPT)?\s+—\s+[A-Z0-9][A-Z0-9_-]*-"
    r"(?:SIGNED|COUNTERSIGNED|SHIP-SIGNED)\b)"
)
TOKEN_RE = re.compile(r"[\w.\-]+", re.UNICODE)
CORPUS_EXTS = (".md", ".html")
CONFIG_NAMES = {".gitignore", ".gitattributes", ".gitmodules", "license", "makefile"}
CONFIG_EXTS = {".json", ".yaml", ".yml", ".toml", ".cfg", ".ini", ".lock"}

README_BODY = """---
rosetta:
  primary_level: L3
  primary_column: Meta
  operator: "Kṛṣṇa ◇"
  tier: "Executive"
  regime: "Vaiśya"
  register: "[S]"
  canonical_phrase: "Canonical registers — derived inventory, additive-only, never hand-edited"
type: register-front-door
title: "00_META/registers — FILE_REGISTER + FOLDER_REGISTER + CLAIM_CARD_REGISTER + CLAIM_GRAPH + CLAIM_LIFECYCLE_INVENTORY"
status: "ACTIVE 2026-07-19 — additive-only remediation wave (receipt 141A gate)"
owner: 01_EMERGENTISM
---
# Canonical Registers — FILE_REGISTER, FOLDER_REGISTER, CLAIM_CARD_REGISTER, CLAIM_GRAPH, CLAIM_LIFECYCLE_INVENTORY

All five JSON files are deterministic derived artifacts. They are navigation,
audit, and routing views; they do not become source authority or evidence by
being present here. Never hand-edit generated entries.

## File and folder inventory

`FILE_REGISTER.json` and `FOLDER_REGISTER.json` are generated from
`git ls-files`, working-tree bytes, and the tracked-directory closure:

```sh
python3 09_TOOLS/01_SCRIPTS/build_magnum_opus_register.py --write
python3 09_TOOLS/01_SCRIPTS/build_magnum_opus_register.py --check
```

FILE_REGISTER and FOLDER_REGISTER carry stable `sha256: "SELF"` markers
because they are cyclic generated outputs; README.md and every other static
register-family file carry their real byte hashes. Fail-closed custody: if any
tracked non-output path is absent from the working tree, both modes return
nonzero and `--write` changes nothing. A staged deletion of a non-output path
lawfully removes that path from the next generated register.

## Claim, graph, and lifecycle registers

`CLAIM_CARD_REGISTER.json`, `CLAIM_GRAPH.json`, and
`CLAIM_LIFECYCLE_INVENTORY.json` are generated together from the claim-card,
adequacy-docket, schema, book-manifest, and declared source contracts owned by
`compile_claim_cards.py`:

```sh
python3 09_TOOLS/02_COMPILERS/compile_claim_cards.py --write
python3 09_TOOLS/02_COMPILERS/compile_claim_cards.py --check
```

Repair an upstream contract first, then regenerate these three downstream
artifacts. Their graph membership, counts, and lifecycle labels confer no
claim authority and do not establish the claims they inventory.

## Custody boundary

Exact generated custody: `--write` restores this README byte-for-byte from the builder; `--check` fails when it is absent or modified.
Additive-only gate (receipt 141A): these files are inventory/navigation only; they authorize no move, tombstone, promotion, or commit.
"""


def git_ls_files():
    out = subprocess.run(
        ["git", "-C", REPO_ROOT, "ls-files", "-z"],
        check=True, capture_output=True,
    ).stdout
    return sorted(p.decode("utf-8", "surrogateescape") for p in out.split(b"\0") if p)


def sha256_file(abs_path):
    h = hashlib.sha256()
    with open(abs_path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_bytes(raw):
    return hashlib.sha256(raw).hexdigest()


def read_frontmatter_text(text):
    """Cheap first-block YAML scan over text; return top-level scalar fields."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    block = []
    for line in lines[1:]:
        if line.strip() == "---":
            break
        block.append(line)
    else:
        return {}
    fields = {}
    for line in block:
        m = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if m:
            val = m.group(2).strip().strip('"').strip("'")
            fields.setdefault(m.group(1), val)
    return fields


def read_frontmatter(abs_path):
    try:
        with open(abs_path, "rb") as fh:
            raw = fh.read(FM_READ_BYTES)
    except OSError:
        return {}
    return read_frontmatter_text(raw.decode("utf-8", "replace"))


def authority_from_status(status):
    if not status:
        return "unrated"
    u = status.upper()
    if "STAGED" in u or "PENDING" in u or "[D]" in u or "DRAFT" in u:
        return "staged"
    if SIGNED_STATUS_RE.search(u):
        return "signed"
    return "unrated"


def evidence_tier_from(fields):
    val = fields.get("evidence_tier")
    if not val:
        return None
    m = TIER_RE.search(val)
    return m.group(0) if m else None


def artifact_class(path):
    top = path.split("/", 1)[0]
    if top in ("90_ARCHIVE", "91_COMPATIBILITY"):
        return "archive"
    if top == "12_PUBLIC_SITE":
        return "site"
    if top == "09_TOOLS":
        return "tool"
    base = path.rsplit("/", 1)[-1]
    low = base.lower()
    stem, ext = os.path.splitext(low)
    if "receipt" in low or "50_audits_and_executions" in path.lower():
        return "receipt"
    if low in CONFIG_NAMES or stem in CONFIG_NAMES or ext in CONFIG_EXTS:
        return "config"
    if ext in (".md", ".markdown"):
        return "doctrine"
    return "other"


def k_relation(path):
    if path in K_EXACT:
        return K_EXACT[path]
    for prefix, k in K_PREFIX:
        if path.startswith(prefix):
            return k
    return None


def map_disposition(raw):
    u = (raw or "").upper()
    if not u:
        return "keep"
    if "ARCHIVE" in u or "TOMBSTONE" in u or "STONE" in u:
        return "tombstone-candidate"
    if "ABSORB" in u or "REVISE" in u or "STAGED" in u or "ROUTE" in u or "SUCCESSION" in u:
        return "staged"
    return "keep"


def load_manifest_dispositions(path, key_col):
    table = {}
    try:
        with open(path, newline="", encoding="utf-8") as fh:
            for row in csv.DictReader(fh):
                key = (row.get(key_col) or "").strip()
                if key:
                    table[key] = map_disposition(row.get("disposition"))
    except OSError:
        pass
    return table


def build_ref_index(tracked, virtual_files):
    """basename -> hit count across tracked .md/.html (single corpus pass)."""
    basenames = {p.rsplit("/", 1)[-1] for p in tracked}
    counts = Counter()
    for rel in tracked:
        if not rel.lower().endswith(CORPUS_EXTS):
            continue
        if rel in virtual_files:
            text = virtual_files[rel].decode("utf-8", "replace")
        else:
            try:
                with open(os.path.join(REPO_ROOT, rel), "rb") as fh:
                    text = fh.read().decode("utf-8", "replace")
            except OSError:
                continue
        for token, n in Counter(TOKEN_RE.findall(text)).items():
            if token in basenames:
                counts[token] += n
    return counts


def file_entry(rel, ref_counts, manifest_disp, virtual_files):
    if rel in CYCLIC_REGISTER_PATHS:
        return self_entry(rel)
    abs_path = os.path.join(REPO_ROOT, rel)
    if rel in virtual_files:
        raw = virtual_files[rel]
        digest = sha256_bytes(raw)
        size = len(raw)
        fields = (
            read_frontmatter_text(raw.decode("utf-8", "replace"))
            if rel.lower().endswith((".md", ".markdown")) else {}
        )
    else:
        digest = sha256_file(abs_path)
        size = os.path.getsize(abs_path)
        fields = read_frontmatter(abs_path) if rel.lower().endswith((".md", ".markdown")) else {}
    base = rel.rsplit("/", 1)[-1]
    top = rel.split("/", 1)[0]
    return {
        "path": rel,
        "sha256": digest,
        "bytes": size,
        "owner_lane": top if "/" in rel else "root",
        "artifact_class": artifact_class(rel),
        "authority_status": authority_from_status(fields.get("status")),
        "evidence_tier": evidence_tier_from(fields),
        "k_relation": k_relation(rel),
        "public_projection": rel if rel.startswith("12_PUBLIC_SITE/") else None,
        "disposition": manifest_disp.get(rel, "keep"),
        "destination": None,
        "absorber": None,
        "inbound_references": min(ref_counts.get(base, 0), REF_CAP),
        "gate": None,
        "review_state": "unreviewed",
    }


def self_entry(rel):
    return {
        "path": rel,
        "sha256": "SELF",
        "bytes": 0,
        "owner_lane": "00_META",
        "artifact_class": "config",
        "authority_status": "unrated",
        "evidence_tier": None,
        "k_relation": None,
        "public_projection": None,
        "disposition": "keep",
        "destination": None,
        "absorber": None,
        "inbound_references": 0,
        "gate": None,
        "review_state": "unreviewed",
    }


def folder_type(path):
    if path == ".":
        return "other"
    top = path.split("/", 1)[0]
    if top in ("00_META", "00_CONTROL"):
        return "meta"
    if top in ("90_ARCHIVE", "91_COMPATIBILITY"):
        return "archive"
    if top == "12_PUBLIC_SITE":
        return "site"
    if top == "09_TOOLS":
        return "tool"
    if top == "10_SEED":
        return "seed"
    if re.match(r"^(0[1-8]|11)_", top):
        return "lane"
    return "other"


def folder_scope_guess(door_abs, virtual_text=None):
    """One-line scope from the front door: canonical_phrase > title > description > first prose line."""
    if not door_abs:
        return None
    fields = read_frontmatter_text(virtual_text) if virtual_text is not None else read_frontmatter(door_abs)
    for key in ("canonical_phrase", "title", "description"):
        val = fields.get(key)
        if val:
            return val[:140]
    if virtual_text is not None:
        text = virtual_text
    else:
        try:
            with open(door_abs, "rb") as fh:
                text = fh.read(FM_READ_BYTES).decode("utf-8", "replace")
        except OSError:
            return None
    in_fm = False
    for line in text.splitlines():
        s = line.strip()
        if s == "---":
            in_fm = not in_fm
            continue
        if in_fm or not s or s.startswith("#") or s.startswith("<!--"):
            continue
        return s[:140]
    return None


def build_folder_entries(tracked, manifest_disp, virtual_files):
    parents = {}
    for rel in tracked:
        d = rel.rsplit("/", 1)[0] if "/" in rel else "."
        parts = d.split("/") if d != "." else ["."]
        for i in range(len(parts)):
            parents.setdefault("/".join(parts[: i + 1]), 0)
        parents[d] += 1
    file_set = set(tracked)
    entries = []
    for folder in sorted(parents):
        prefix = "" if folder == "." else folder + "/"
        door = None
        for name in ("README.md", "AGENTS.md", "index.html"):
            cand = prefix + name
            if cand in file_set:
                door = cand
                break
        door_abs = os.path.join(REPO_ROOT, door) if door else None
        door_virtual = virtual_files.get(door)
        door_text = door_virtual.decode("utf-8", "replace") if door_virtual is not None else None
        door_fields = (
            read_frontmatter_text(door_text) if door_text is not None
            else read_frontmatter(door_abs) if door and door.lower().endswith(".md")
            else {}
        )
        count = sum(1 for rel in tracked if rel.startswith(prefix)) if prefix else len(tracked)
        entries.append({
            "path": folder,
            "type": folder_type(folder),
            "nearest_front_door": door,
            "front_door_requirement": "present" if door else "missing",
            "owns": folder_scope_guess(door_abs, door_text),
            "must_not_own": None,
            "status": authority_from_status(door_fields.get("status")),
            "tracked_file_count": count,
            "disposition": manifest_disp.get(folder, "keep"),
            "gate": None,
            "review_state": "unreviewed",
        })
    return entries


def derive(tracked, virtual_files=None):
    virtual_files = virtual_files or {}
    file_disp = load_manifest_dispositions(FILE_MANIFEST, "path")
    folder_disp = load_manifest_dispositions(FOLDER_MANIFEST, "folder")
    ref_counts = build_ref_index(tracked, virtual_files)
    file_entries = [file_entry(rel, ref_counts, file_disp, virtual_files) for rel in tracked]
    file_entries.sort(key=lambda e: e["path"])
    folder_entries = build_folder_entries(tracked, folder_disp, virtual_files)
    file_doc = {
        "schema": FILE_SCHEMA,
        "generator": REGISTER_GENERATOR,
        "source": FILE_SOURCE,
        "entry_count": len(file_entries),
        "entries": file_entries,
    }
    folder_doc = {
        "schema": FOLDER_SCHEMA,
        "generator": REGISTER_GENERATOR,
        "source": FOLDER_SOURCE,
        "entry_count": len(folder_entries),
        "entries": folder_entries,
    }
    return file_doc, folder_doc


def dump(doc, abs_path):
    with open(abs_path, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, ensure_ascii=False, indent=2)
        fh.write("\n")


def missing_tracked_paths(tracked, allow_generated_outputs=False):
    allowed = GENERATED_OUTPUT_PATHS if allow_generated_outputs else frozenset()
    return [
        rel for rel in tracked
        if rel not in allowed and not os.path.lexists(os.path.join(REPO_ROOT, rel))
    ]


def validate_document(rel, doc, derived):
    """Validate shape and metadata before any path-keyed diagnostic mapping."""
    errors = []
    if type(doc) is not dict:
        return [f"document must be an object, got {type(doc).__name__}"]
    actual_keys = frozenset(doc)
    if actual_keys != DOCUMENT_KEYS:
        missing = sorted(DOCUMENT_KEYS - actual_keys)
        extra = sorted(actual_keys - DOCUMENT_KEYS)
        errors.append(f"top-level keys differ (missing={missing}, extra={extra})")
    for field in ("schema", "generator", "source"):
        if doc.get(field) != derived[field]:
            errors.append(f"{field} must be {derived[field]!r}, got {doc.get(field)!r}")
    entries = doc.get("entries")
    if type(entries) is not list:
        errors.append(f"entries must be a list, got {type(entries).__name__}")
        return errors
    count = doc.get("entry_count")
    if type(count) is not int:
        errors.append(f"entry_count must be an integer, got {type(count).__name__}")
    elif count != len(entries):
        errors.append(f"entry_count={count} but entries has {len(entries)} rows")
    paths = []
    for index, entry in enumerate(entries):
        if type(entry) is not dict:
            errors.append(f"entries[{index}] must be an object, got {type(entry).__name__}")
            continue
        path = entry.get("path")
        if type(path) is not str or not path:
            errors.append(f"entries[{index}].path must be a non-empty string")
            continue
        paths.append(path)
    duplicates = sorted(path for path, count in Counter(paths).items() if count > 1)
    if duplicates:
        errors.append(f"duplicate entry paths: {duplicates[:10]}")
    return errors


def diff_docs(derived, on_disk):
    d_entries = {e["path"]: e for e in derived["entries"]}
    o_entries = {e["path"]: e for e in on_disk["entries"]}
    added = sorted(set(d_entries) - set(o_entries))
    removed = sorted(set(o_entries) - set(d_entries))
    changed = []
    for p in sorted(set(d_entries) & set(o_entries)):
        if d_entries[p] != o_entries[p]:
            fields = [k for k in d_entries[p] if d_entries[p].get(k) != o_entries[p].get(k)]
            changed.append((p, fields[:4]))
    return added, removed, changed


def report_missing(missing, mode):
    print(f"ERROR: {len(missing)} index-tracked path(s) are missing from the working tree; --{mode} refused")
    for rel in missing[:50]:
        print(f"  missing {rel}")
    if len(missing) > 50:
        print(f"  ... and {len(missing) - 50} more")
    print("Restore each path, or stage an authorized deletion before regenerating.")


def report_untracked_outputs(untracked, mode):
    print(f"ERROR: declared generated output(s) are absent from the git index; --{mode} refused")
    for rel in untracked:
        print(f"  untracked-output {rel}")
    print("Restore the index custody of these outputs before regenerating.")


def main():
    ap = argparse.ArgumentParser(description="Build/check Magnum Opus canonical registers (completion plan §2).")
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="generate FILE_REGISTER.json + FOLDER_REGISTER.json")
    mode.add_argument("--check", action="store_true", help="re-derive and report drift (exit 1 on drift)")
    args = ap.parse_args()

    try:
        tracked = git_ls_files()
    except (OSError, subprocess.CalledProcessError) as exc:
        print(f"ERROR: could not enumerate tracked files: {exc}")
        return 1

    untracked_outputs = sorted(GENERATED_OUTPUT_PATHS - set(tracked))
    if untracked_outputs:
        report_untracked_outputs(untracked_outputs, "write" if args.write else "check")
        return 1

    missing = missing_tracked_paths(tracked, allow_generated_outputs=args.write)
    if missing:
        report_missing(missing, "write" if args.write else "check")
        return 1

    if args.write:
        try:
            virtual_files = {README_REL: README_BODY.encode("utf-8")}
            file_doc, folder_doc = derive(tracked, virtual_files)
            for rel, doc in ((FILE_REG_REL, file_doc), (FOLDER_REG_REL, folder_doc)):
                errors = validate_document(rel, doc, doc)
                if errors:
                    print(f"ERROR: generated {rel} is invalid")
                    for error in errors:
                        print(f"  {error}")
                    return 1
            os.makedirs(REG_DIR, exist_ok=True)
            dump(file_doc, os.path.join(REG_DIR, "FILE_REGISTER.json"))
            dump(folder_doc, os.path.join(REG_DIR, "FOLDER_REGISTER.json"))
            with open(os.path.join(REG_DIR, "README.md"), "w", encoding="utf-8") as fh:
                fh.write(README_BODY)
        except OSError as exc:
            print(f"ERROR: --write refused after a working-tree read/write failure: {exc}")
            return 1
        print(f"wrote {FILE_REG_REL} ({file_doc['entry_count']} entries)")
        print(f"wrote {FOLDER_REG_REL} ({folder_doc['entry_count']} entries)")
        print(f"restored exact {README_REL}")
        return 0

    try:
        file_doc, folder_doc = derive(tracked)
    except OSError as exc:
        print(f"ERROR: --check refused after a working-tree read failure: {exc}")
        return 1

    drift = False
    readme_abs = os.path.join(REPO_ROOT, README_REL)
    try:
        with open(readme_abs, "rb") as fh:
            readme_raw = fh.read()
    except OSError as exc:
        print(f"DRIFT {README_REL}: unreadable on disk ({exc})")
        drift = True
    else:
        if readme_raw != README_BODY.encode("utf-8"):
            print(f"DRIFT {README_REL}: content differs from exact generated README_BODY")
            drift = True

    for rel, derived in ((FILE_REG_REL, file_doc), (FOLDER_REG_REL, folder_doc)):
        abs_path = os.path.join(REPO_ROOT, rel)
        try:
            with open(abs_path, encoding="utf-8") as fh:
                on_disk = json.load(fh)
        except (OSError, json.JSONDecodeError) as exc:
            print(f"DRIFT {rel}: unreadable on disk ({exc})")
            drift = True
            continue
        errors = validate_document(rel, on_disk, derived)
        if errors:
            print(f"INVALID {rel}:")
            for error in errors:
                print(f"  {error}")
            drift = True
            continue
        if on_disk != derived:
            drift = True
            added, removed, changed = diff_docs(derived, on_disk)
            print(f"DRIFT {rel}: +{len(added)} added, -{len(removed)} removed, ~{len(changed)} changed")
            for p in added[:25]:
                print(f"  added   {p}")
            for p in removed[:25]:
                print(f"  removed {p}")
            for p, fields in changed[:25]:
                print(f"  changed {p} ({', '.join(fields)})")
            if not added and not removed and not changed:
                print("  document ordering or non-entry metadata differs")
        else:
            print(f"clean {rel} ({derived['entry_count']} entries)")
    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main())
